<a href="https://colab.research.google.com/github/Sanjayme049/EDA/blob/main/numpy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd

In [4]:
mat = np.arange(1,26).reshape(5,5)

In [5]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [8]:
mat[3,4]

20

In [9]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [10]:
mat[4]

array([21, 22, 23, 24, 25])

In [11]:
mat.sum()

325

In [12]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [13]:
var1=np.array([[9,8,7],[4,5,6]])

In [14]:
var1[0][1]

8

In [15]:
ages={'Sam':5,'Frank':10,'Spike':7}

In [20]:
pd.Series(ages)

Sam       5
Frank    10
Spike     7
dtype: int64

In [23]:
ages['Sam']

5

In [24]:
ages.keys()

dict_keys(['Sam', 'Frank', 'Spike'])

In [25]:
ages.values()

dict_values([5, 10, 7])