<a href="https://colab.research.google.com/github/Sanjayme049/EDA/blob/main/numpy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
mat = np.arange(1,26).reshape(5,5)

In [13]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
mat[3,4]

20

In [21]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [23]:
mat[4]

array([21, 22, 23, 24, 25])

In [24]:
mat.sum()

325

In [25]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])