<a href="https://colab.research.google.com/github/Sanjayme049/EDA/blob/main/random_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
rng = np.random.default_rng(seed=42)
arr2 =rng.random((3,3))

In [2]:
arr2

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [3]:
np.random.randint(0,101,5)

array([88, 64,  6,  2, 25])

In [4]:
np.random.randint(100)

26

In [5]:
np.random.randint(0,100,10)

array([75, 42, 24, 40, 48, 14, 77, 66, 69, 68])

In [7]:
np.random.randint(0,100,10)

array([95, 31, 24, 56,  1, 49, 91, 58, 79, 53])